apiVersion: v1
kind: Service
metadata:
  name: testeks-svc
  labels:
    app: testeks
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: testeks
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testeks-v1
spec:
  replicas: 1
  selector:
      matchLabels:
        app: testeks
  template:
    metadata:
      labels:
        app: testeks
        version: v1     
    spec:
      containers:
      - name: testeks
        image: 938784100097.dkr.ecr.eu-west-2.amazonaws.com/testeks:1.0
        imagePullPolicy: Always        
        resources:
          requests:
            cpu: 300m
          limits:
            cpu: 1024m
        ports:
        - containerPort: 8080